"""empty message

Revision ID: 3ec624ff09b2
Revises: 
Create Date: 2020-05-22 17:47:29.375338

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ec624ff09b2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('text')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('application_id', sa.String(length=100), nullable=True),
    sa.Column('age', sa.String(length=3), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('networks', sa.String(length=150), nullable=True),
    sa.Column('about_me', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('application_id')
    )
    op.create_table('interests_user',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('interest_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['interest_id'], ['interests.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.create_table('show_profile',
    sa.Column('showed_profile_id', sa.Integer(), nullable=True),
    sa.Column('sight_profile_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['showed_profile_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['sight_profile_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('show_profile')
    op.drop_table('interests_user')
    op.drop_table('user')
    op.drop_table('interests')
    # ### end Alembic commands ###
