"""empty message

Revision ID: c0b3a4c4fcd9
Revises: 26c9d3cdabb8
Create Date: 2020-05-19 16:21:15.660107

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0b3a4c4fcd9'
down_revision = '26c9d3cdabb8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('show_profile',
    sa.Column('showed_profile_id', sa.Integer(), nullable=True),
    sa.Column('sight_profile_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['showed_profile_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['sight_profile_id'], ['user.id'], )
    )
    op.add_column('user', sa.Column('application_id', sa.String(length=100), nullable=True))
    op.create_unique_constraint(None, 'user', ['application_id'])
    op.drop_column('user', 'status_dialog')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('status_dialog', sa.VARCHAR(length=30), nullable=True))
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'application_id')
    op.drop_table('show_profile')
    # ### end Alembic commands ###
